//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASSysMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MrpAgentTask
    {
        public int ID { get; set; }
        public string TaskName { get; set; }
        public string TaskSP { get; set; }
        public System.DateTime Runtime { get; set; }
        public string Interval { get; set; }
        public Nullable<bool> Activate { get; set; }
        public string Description { get; set; }
    }
}
