//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASSysMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MrpAgentTaskStatu
    {
        public long StatusId { get; set; }
        public int TaskId { get; set; }
        public int DBId { get; set; }
        public string DatabaseName { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public string Status { get; set; }
    }
}
