//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASSysMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPExceptionLog
    {
        public int MRPID { get; set; }
        public string StoredProcedure { get; set; }
        public Nullable<int> PartID { get; set; }
        public Nullable<int> MethodID { get; set; }
        public Nullable<int> VersionID { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string OrderNumber { get; set; }
        public string LineNumber { get; set; }
        public string Error { get; set; }
    
        public virtual MRPLog MRPLog { get; set; }
    }
}
