//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASSysMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPLock
    {
        public int MRPLockID { get; set; }
        public int MRPEmpID { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
