//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASSysMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPLog
    {
        public int MRPID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime StartMRPOn { get; set; }
        public Nullable<System.DateTime> FinishMRPOn { get; set; }
        public short MRPStatus { get; set; }
    
        public virtual MRPExceptionLog MRPExceptionLog { get; set; }
    }
}
