//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASSysMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPMonitorEntry
    {
        public int MRPMonitor_ID { get; set; }
        public int UID { get; set; }
        public int MRPID { get; set; }
        public System.DateTime StartMRPOn { get; set; }
        public System.DateTime FinishMRPOn { get; set; }
        public string MRPStatus { get; set; }
        public int Duration { get; set; }
        public int NewWOSuggs { get; set; }
        public int NewPOSuggs { get; set; }
        public int RescheduleWOSuggs { get; set; }
        public int ReschedulePOSuggs { get; set; }
        public int CancelWOSuggs { get; set; }
        public int CancelPOSuggs { get; set; }
        public System.DateTime TimeChecked { get; set; }
    }
}
