//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASSysMon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SQL02Thas01Entities : DbContext
    {
        public SQL02Thas01Entities()
            : base("name=SQL02Thas01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MRPLock> MRPLocks { get; set; }
        public virtual DbSet<MRPLog> MRPLogs { get; set; }
        public virtual DbSet<MRPExceptionLog> MRPExceptionLogs { get; set; }
    
        public virtual ObjectResult<THAS_CONNECT_MRPChecker_Result> THAS_CONNECT_MRPChecker()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_MRPChecker_Result>("THAS_CONNECT_MRPChecker");
        }
    }
}
